#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

pkill -U "$USER" -x gpg-agent
# Print the message.
# cat <<-EOF

# Thank you. Come again!
#   -- Dr. Apu Nahasapeemapetilon
# EOF
