#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export XAUTHORITY="${XDG_CACHE_HOME}/xorg/Xauthority"
export PULSE_COOKIE="${XDG_CACHE_HOME}/pulseaudio/cookie"

export GIMP2_DIRECTORY="${XDG_DATA_HOME}/gimp"
export IPYTHONDIR="${XDG_DATA_HOME}/ipython"
export PYLINTHOME="${XDG_DATA_HOME}/pylint"
export VIMPERATOR_RUNTIME="${XDG_DATA_HOME}/vimperator"

export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"

export DATADIR='/data'
export CARGO_HOME="${DATADIR}/storage/cargo"
export PATH="${PATH}:${CARGO_HOME}/bin"
export GOPATH="${DATADIR}/storage/gopath"
export GOBIN="${GOPATH}/bin"
export PATH="${PATH}:${GOBIN}"
export PYTHONPATH="${DATADIR}/scripts/lib/python"
export PYTHONUSERBASE="${DATADIR}/storage/python"
export MYPYPATH="${PYTHONPATH}"
export RUSTUP_HOME="${DATADIR}/storage/multirust"

export ESCDELAY='0'
export KEYTIMEOUT='1'

export QT_QPA_PLATFORMTHEME='gtk2'
export RANGER_LOAD_DEFAULT_RC='FALSE'

#
# Browser
#

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='pager'
export MANPAGER='pager-man'

#
# Language
#

if [[ -z "${LANG}" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
#
# Temporary Files
#

if [[ ! -d "${TMPDIR}" ]]; then
  export TMPDIR="/tmp/${LOGNAME}"
  mkdir -p -m 700 "${TMPDIR}"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

umask 027
