#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export DATADIR='/data'

export QT_STYLE_OVERRIDE='gtk'
export RANGER_LOAD_DEFAULT_RC='FALSE'
export XAUTHORITY="${XDG_CACHE_HOME}/xorg/Xauthority"
export PULSE_COOKIE="${XDG_CACHE_HOME}/pulseaudio/cookie"
export VIMPERATOR_RUNTIME="${XDG_CACHE_HOME}/vimperator"

export ASPROOT="${XDG_DATA_HOME}/asp"
export GIMP2_DIRECTORY="${XDG_DATA_HOME}/gimp"
export IPYTHONDIR="${XDG_DATA_HOME}/ipython"
export PYLINTHOME="${XDG_DATA_HOME}/pylint"
export WINEPREFIX="${XDG_DATA_HOME}/wine"

export VIMINIT='let $MYVIMRC="${XDG_CONFIG_HOME}/vim/vimrc" | source ${MYVIMRC}'
export VIMPERATOR_INIT=":source ${XDG_CONFIG_HOME}/vimperator/init"
export SYSSCREENRC="${XDG_CONFIG_HOME}/screen.conf"
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"
export SSH_AUTH_SOCK="${GNUPGHOME}/S.gpg-agent.ssh"

export GOPATH="${DATADIR}/storage/gopath"
export CARGO_HOME="${DATADIR}/storage/cargo_home"

export ESCDELAY='0'

#
# Browser
#

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='vimpager'
export MANPAGER='manpager'

#
# Language
#

if [[ -z "${LANG}" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
#
# Temporary Files
#

if [[ ! -d "${TMPDIR}" ]]; then
  export TMPDIR="/tmp/${LOGNAME}"
  mkdir -p -m 700 "${TMPDIR}"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
