#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

stty -ixon

export GPG_TTY="$( tty )"

ssh_array=('rservy' 'nservy')
for remote in $ssh_array; do
    alias "$remote"="ssh $remote"
    alias "m$remote"="sshfs ${remote}:/ /remote/$remote"
    alias "um$remote"="fusermount -u /remote/$remote"
done
unset ssh_array

bindkey -rpM viins ''
bindkey -rpM vicmd ''
bindkey -rpM viopp ''
bindkey -rpM visual ''

bindkey -RM viins '0-9' self-insert
bindkey -RM viins 'a-z' self-insert
bindkey -RM viins 'A-Z' self-insert
bindkey -RM viins '!-~' self-insert
bindkey -RM viins '^A-^Z' self-insert
bindkey -RM viins '^!-^~' self-insert
bindkey -M viins '^D' list-choices
bindkey -M viins '^E' edit-command-line
bindkey -M viins '^I' expand-or-complete-with-indicator
bindkey -M viins '^L' clear-screen
bindkey -M viins '^M' accept-line
bindkey -M viins '^R' redisplay
bindkey -M viins '^U' vi-kill-line
bindkey -M viins '^W' vi-backward-kill-word
bindkey -M viins '^[' vi-cmd-mode
bindkey -M viins '^P' expand-cmd-path
bindkey -M viins '^[[A' history-substring-search-up
bindkey -M viins '^[[B' history-substring-search-down
bindkey -M viins '^[[C' forward-char
bindkey -M viins '^[[D' backward-char
bindkey -M viins '^[OA' history-substring-search-up
bindkey -M viins '^[OB' history-substring-search-down
bindkey -M viins '^[OC' forward-char
bindkey -M viins '^[OD' backward-char
bindkey -M viins '^[[Z' reverse-menu-complete
bindkey -M viins '^[[200~' bracketed-paste
bindkey -M viins ' ' magic-space
bindkey -M viins '^?' backward-delete-char

bindkey -M vicmd '^D' list-choices
bindkey -M vicmd '^L' clear-screen
bindkey -M vicmd '^M' accept-line
bindkey -M vicmd '^E' edit-command-line
bindkey -M vicmd 'X' redo
bindkey -M vicmd '^[[A' up-history
bindkey -M vicmd '^[[B' down-history
bindkey -M vicmd '^[OA' up-history
bindkey -M vicmd '^[OB' down-history
bindkey -M vicmd '^[[200~' bracketed-paste
bindkey -M vicmd '"' vi-set-buffer
bindkey -M vicmd 'gcc' vi-pound-insert
bindkey -M vicmd '$' vi-end-of-line
bindkey -M vicmd '%' vi-match-bracket
bindkey -M vicmd ',' vi-rev-repeat-find
bindkey -M vicmd '.' vi-repeat-change
bindkey -M vicmd '/' history-incremental-pattern-search-forward
bindkey -M vicmd '0' vi-digit-or-beginning-of-line
bindkey -RM vicmd '1-9' digit-argument
bindkey -M vicmd ';' vi-repeat-find
bindkey -M vicmd '?' history-incremental-pattern-search-backward
bindkey -M vicmd 'A' vi-add-eol
bindkey -M vicmd 'B' vi-backward-blank-word
bindkey -M vicmd 'C' vi-change-eol
bindkey -M vicmd 'D' vi-kill-eol
bindkey -M vicmd 'J' vi-forward-blank-word-end
bindkey -M vicmd 'F' vi-find-prev-char
bindkey -M vicmd 'G' vi-fetch-history
bindkey -M vicmd 'I' vi-insert-bol
bindkey -M vicmd '&' vi-join
bindkey -M vicmd 'N' vi-rev-repeat-search
bindkey -M vicmd 'O' vi-open-line-above
bindkey -M vicmd 'P' vi-put-before
bindkey -M vicmd 'R' vi-replace
bindkey -M vicmd 'S' vi-change-whole-line
bindkey -M vicmd 'V' visual-line-mode
bindkey -M vicmd 'W' vi-forward-blank-word
bindkey -M vicmd 'l' vi-backward-delete-char
bindkey -M vicmd '^' vi-first-non-blank
bindkey -M vicmd 'a' vi-add-next
bindkey -M vicmd 'b' vi-backward-word
bindkey -M vicmd 'c' vi-change
bindkey -M vicmd 'd' vi-delete
bindkey -M vicmd 'j' vi-forward-word-end
bindkey -M vicmd 'f' vi-find-next-char
bindkey -M vicmd 'gJ' vi-backward-blank-word-end
bindkey -M vicmd '^G' what-cursor-position
bindkey -M vicmd 'gj' vi-backward-word-end
bindkey -M vicmd 'gg' beginning-of-buffer-or-history
bindkey -M vicmd 'h' vi-backward-char
bindkey -M vicmd 'i' vi-insert
bindkey -M vicmd 'e' history-substring-search-down
bindkey -M vicmd 'u' history-substring-search-up
bindkey -M vicmd 't' vi-forward-char
bindkey -M vicmd 'n' vi-repeat-search
bindkey -M vicmd 'o' vi-open-line-below
bindkey -M vicmd 'p' vi-put-after
bindkey -M vicmd 'r' vi-replace-chars
bindkey -M vicmd 's' vi-substitute
bindkey -M vicmd 'T' vi-find-next-char-skip
bindkey -M vicmd 'x' undo
bindkey -M vicmd 'v' visual-mode
bindkey -M vicmd 'w' vi-forward-word
bindkey -M vicmd 'l' vi-delete-char
bindkey -M vicmd 'y' vi-yank
bindkey -M vicmd 'Y' vi-yank-eol
bindkey -M vicmd '~' vi-oper-swap-case

bindkey -M viopp '^[' vi-cmd-mode
bindkey -M viopp '^[OA' up-line
bindkey -M viopp '^[OB' down-line
bindkey -M viopp '^[[A' up-line
bindkey -M viopp '^[[B' down-line
bindkey -M viopp 'aW' select-a-blank-word
bindkey -M viopp 'aa' select-a-shell-word
bindkey -M viopp 'aw' select-a-word
bindkey -M viopp 'iW' select-in-blank-word
bindkey -M viopp 'ia' select-in-shell-word
bindkey -M viopp 'iw' select-in-word
bindkey -M viopp 'e' down-line
bindkey -M viopp 'u' up-line

bindkey -M visual '^[OA' up-line
bindkey -M visual '^[OB' down-line
bindkey -M visual '^[[A' up-line
bindkey -M visual '^[[B' down-line
bindkey -M visual 'aW' select-a-blank-word
bindkey -M visual 'aa' select-a-shell-word
bindkey -M visual 'aw' select-a-word
bindkey -M visual 'iW' select-in-blank-word
bindkey -M visual 'ia' select-in-shell-word
bindkey -M visual 'iw' select-in-word
bindkey -M visual 'e' down-line
bindkey -M visual 'u' up-line
bindkey -M visual 'o' exchange-point-and-mark
bindkey -M visual 'p' put-replace-selection
bindkey -M visual 'l' vi-delete
bindkey -M visual '~' vi-oper-swap-case
